package com.lara8;

public class SerialversionUID 
{
	private static final long serialVersionUID = 4038305141805077716L;
	/*
	Java run-time associates with each serializable class a special version number known as serialVersionUID. 
	This number is later used
	 during deserialization process to verify if the application which performed the serialization and the application 
	 which is doing the 
	 deserialization have loaded and use compatible Java classes (with respect to serialization). If the receiver has loaded a class which 
	 has the same name but different serialVersionUID, the Java run-time will report a problem by throwing an exception of type 
	 InvalidClassException.
	
	Defining serialVersionUID

	A serializable class can specify its own serialVersionUID value explicitly by declaring a static, final field of name serialVersionUID 
	and of type long:

	private static final long serialVersionUID = 4038305141805077716L;
	
	The access modifier does not really matter but private is commonly used.

	If serial version is not explicitly declared, it will be automatically generated by compiler and stored in the class file. The compiler 
	calculates default serialVersionUID value based on several aspects of the class like its name, its all public and protected members
	 and so on.

	The default serialVersionUID calculation may vary between compilers so it may give different results in different environments. 
	To ensure a consistent serialVersionUID value, it is strongly recommended to explicitly declare its value.
	*/
}
